export type Day = {
  n: number;
  week: 1 | 2 | 3;
  weekTheme: string;
  focus: string;
  focusDesc: string;
  audioTitle: string;
  audioDuration: string; // mm:ss placeholder
  audioUrl?: string; // hot-link the recording here when ready
  reflection: string;
  action: string;
  actionPrinciple: string;
  morningIntention: string;
  textNudge: string;
  eveningReflection: string;
  commandMove: string;
};

export const WEEK_THEME: Record<1 | 2 | 3, string> = {
  1: "Truth & Clarity",
  2: "Build the Engine",
  3: "Live in Command",
};

export const DAYS: Day[] = [
  { n: 1, week: 1, weekTheme: "Truth & Clarity", focus: "Choose Command", focusDesc: "Decide to run your business from Truth, not fear.", audioTitle: "Day 1: The Command Shift Begins", audioDuration: "2:36", audioUrl: "/audio/day-01.m4a", reflection: "Where in my business do I feel most scattered or reactive?", action: "Write one sentence naming your commitment for these 21 days.", actionPrinciple: "The shift begins with a decision.", morningIntention: "I lead this business from clarity, not fear.", textNudge: "You don't have a hustle problem — you have an alignment problem.", eveningReflection: "What did choosing command feel like today?", commandMove: "Write and post your 21-day commitment." },
  { n: 2, week: 1, weekTheme: "Truth & Clarity", focus: "Your Mission", focusDesc: "Reconnect with why the business truly exists.", audioTitle: "Day 2: The Truth Beneath Your Business", audioDuration: "2:40", audioUrl: "/audio/day-02.m4a", reflection: "Why does this business exist, beyond the income?", action: "Write one honest mission line.", actionPrinciple: "A business built on Truth doesn't have to be forced.", morningIntention: "My business is an expression of my Truth.", textNudge: "A business built on Truth doesn't have to be pushed.", eveningReflection: "When did my work feel most true today?", commandMove: "Draft one honest mission line." },
  { n: 3, week: 1, weekTheme: "Truth & Clarity", focus: "See It Clearly", focusDesc: "An honest read on where your business stands.", audioTitle: "Day 3: The Honest Command Audit", audioDuration: "2:43", audioUrl: "/audio/day-03.m4a", reflection: "What am I most afraid I'll see if I look honestly?", action: "Rate each core area 1–5, then circle your two lowest.", actionPrinciple: "The Truth shows you the way forward.", morningIntention: "I face my business with honesty and love.", textNudge: "You can't command what you won't look at.", eveningReflection: "What did my honest audit reveal?", commandMove: "Run the Command Audit and mark your two lowest areas." },
  { n: 4, week: 1, weekTheme: "Truth & Clarity", focus: "Make Room", focusDesc: "Release what's quietly draining your business.", audioTitle: "Day 4: Clear the Hustle Clutter", audioDuration: "2:36", audioUrl: "/audio/day-04.m4a", reflection: "What did I say yes to out of fear, not alignment?", action: "Release one thing today — a tool, task, or commitment.", actionPrinciple: "Every aligned “no” makes room for a truer “yes.”", morningIntention: "I release what drains me and make room for what aligns.", textNudge: "Command subtracts. Let something go today.", eveningReflection: "What felt lighter after I let go?", commandMove: "Release one draining tool or commitment." },
  { n: 5, week: 1, weekTheme: "Truth & Clarity", focus: "Set Your Heading", focusDesc: "Choose the one destination that matters most.", audioTitle: "Day 5: Name Your True North", audioDuration: "2:40", audioUrl: "/audio/day-05.m4a", reflection: "If only one thing improved in 90 days, what would shift the most?", action: "Write your True North for this season in one sentence.", actionPrinciple: "Clarity is knowing what matters most.", morningIntention: "I know my heading. I move toward it on purpose.", textNudge: "One clear heading beats a dozen half-pursued directions.", eveningReflection: "Did today move me toward my True North?", commandMove: "Name your True North in one sentence." },
  { n: 6, week: 1, weekTheme: "Truth & Clarity", focus: "Guard Your Capacity", focusDesc: "Protect the leader the business depends on.", audioTitle: "Day 6: Protect the Command Seat", audioDuration: "2:34", audioUrl: "/audio/day-06.m4a", reflection: "Where am I the bottleneck everything waits on?", action: "Set one real boundary today.", actionPrinciple: "You can't lead from the bottom of your own to-do list.", morningIntention: "I protect my capacity because I lead this business.", textNudge: "Boundaries aren't restrictions — they're how you stay clear.", eveningReflection: "What boundary did I honor today?", commandMove: "Set and defend one boundary." },
  { n: 7, week: 1, weekTheme: "Truth & Clarity", focus: "Pause & Review", focusDesc: "See your first week's foundation take shape.", audioTitle: "Day 7: Week One Snapshot", audioDuration: "2:29", audioUrl: "/audio/day-07.m4a", reflection: "What became clearer about my business this week?", action: "Reread your commitment, mission, and True North together.", actionPrinciple: "What you review, you can command.", morningIntention: "I build my business on purpose.", textNudge: "Command is built in the pause.", eveningReflection: "What's the one shift I carry into next week?", commandMove: "Review Week 1 and name your carry-forward shift." },
  { n: 8, week: 2, weekTheme: "Build the Engine", focus: "Sharpen the Offer", focusDesc: "Align what you sell with your mission.", audioTitle: "Day 8: Your Offer, Built on Truth", audioDuration: "2:25", audioUrl: "/audio/day-08.m4a", reflection: "Does my offer reflect my mission and True North?", action: "Write your core offer in one clear sentence.", actionPrinciple: "An aligned offer sells itself.", morningIntention: "My offer is an honest expression of the value I create.", textNudge: "If it feels forced to sell, it may be out of alignment.", eveningReflection: "Where did my offer feel most aligned today?", commandMove: "Write your offer in one clear sentence." },
  { n: 9, week: 2, weekTheme: "Build the Engine", focus: "Follow the Money", focusDesc: "See how revenue actually moves.", audioTitle: "Day 9: The Revenue Engine", audioDuration: "2:34", audioUrl: "/audio/day-09.m4a", reflection: "Where does my buying path stall or leak?", action: "Take one aligned revenue move — clarify a price, simplify a step, or follow up a lead.", actionPrinciple: "Hustle chases more; command clears the path.", morningIntention: "I direct how value flows, on purpose.", textNudge: "Hustle chases more. Command clears the path.", eveningReflection: "What friction did I remove today?", commandMove: "Clear one point of revenue friction." },
  { n: 10, week: 2, weekTheme: "Build the Engine", focus: "Build a System", focusDesc: "Move work out of your head.", audioTitle: "Day 10: Free Yourself From the Bottleneck", audioDuration: "2:31", audioUrl: "/audio/day-10.m4a", reflection: "What do I rebuild from scratch every week?", action: "Systematize one thing — a checklist, template, or rule.", actionPrinciple: "If it lives only in your head, it owns you.", morningIntention: "I build systems that hold my business, so I can lead it.", textNudge: "Systems are love, made repeatable.", eveningReflection: "What will now run without me?", commandMove: "Turn one repeated task into a system." },
  { n: 11, week: 2, weekTheme: "Build the Engine", focus: "Sound Like You", focusDesc: "Reclaim your true, defensible voice.", audioTitle: "Day 11: Find Your Brand Voice", audioDuration: "2:25", audioUrl: "/audio/day-11.m4a", reflection: "Whose voice have I been imitating that isn't mine?", action: "Rewrite one piece of copy so it sounds like you.", actionPrinciple: "Truth is the one thing no one can copy.", morningIntention: "I speak from Truth. My voice is my signature.", textNudge: "Sameness is invisible. Sound like yourself.", eveningReflection: "Where did I sound most like me today?", commandMove: "Rewrite one piece of copy in your true voice." },
  { n: 12, week: 2, weekTheme: "Build the Engine", focus: "Plant Your Flag", focusDesc: "Own your specific place in the market.", audioTitle: "Day 12: Claim Your Position", audioDuration: "2:31", audioUrl: "/audio/day-12.m4a", reflection: "Who am I truly the best choice for — and who am I not for?", action: "Write your positioning in one line.", actionPrinciple: "When you try to be for everyone, you're compelling to no one.", morningIntention: "I am the aligned choice for the people I'm here to serve.", textNudge: "Clear positioning wins the right people.", eveningReflection: "Did I speak to my true-fit client today?", commandMove: "Write your one-line positioning." },
  { n: 13, week: 2, weekTheme: "Build the Engine", focus: "Your Daily Rhythm", focusDesc: "Build the habit that keeps clarity renewed.", audioTitle: "Day 13: Install the Daily Compass", audioDuration: "2:35", audioUrl: "/audio/day-13.m4a", reflection: "What would I need to see each morning to lead from clarity?", action: "Design a 3-question morning check-in and do it once today.", actionPrinciple: "Command is not a moment — it's a habit.", morningIntention: "I begin each day in command.", textNudge: "Five quiet minutes beats any burst of hustle.", eveningReflection: "Did my compass guide my day?", commandMove: "Design and run your Daily Compass once." },
  { n: 14, week: 2, weekTheme: "Build the Engine", focus: "Trust the Build", focusDesc: "Protect the engine you've built.", audioTitle: "Day 14: Week Two Snapshot", audioDuration: "2:40", audioUrl: "/audio/day-14.m4a", reflection: "Where am I tempted to abandon good work too early?", action: "Reread Weeks 1–2 and choose the one thing to protect.", actionPrinciple: "Trust the build, even when it's still under construction.", morningIntention: "Every aligned step is working.", textNudge: "Command lays the stones and lets them set.", eveningReflection: "What did I build this week worth keeping?", commandMove: "Choose the one build to protect this week." },
  { n: 15, week: 3, weekTheme: "Live in Command", focus: "Consolidate", focusDesc: "Bring it all into one clear view.", audioTitle: "Day 15: One Command Center", audioDuration: "2:37", audioUrl: "/audio/day-15.m4a", reflection: "Where does my business information actually live right now?", action: "Build one command view: mission, True North, priorities, numbers.", actionPrinciple: "You can't lead what you can't see in one place.", morningIntention: "I lead from one clear command center.", textNudge: "Overwhelm is fracture. Command consolidates.", eveningReflection: "What did seeing it all in one place change?", commandMove: "Build your one-page command center." },
  { n: 16, week: 3, weekTheme: "Live in Command", focus: "Motion vs. Progress", focusDesc: "Aim your energy at what truly matters.", audioTitle: "Day 16: Aligned Action Over Busywork", audioDuration: "2:42", audioUrl: "/audio/day-16.m4a", reflection: "What “busy” am I using to avoid the bigger, aligned move?", action: "Take the first step on your highest-leverage action today.", actionPrinciple: "The universe supports a made-up mind.", morningIntention: "I choose aligned action over busywork.", textNudge: "One aligned move beats a full day of reacting.", eveningReflection: "Did my energy go where it mattered?", commandMove: "Take step one on your highest-leverage move." },
  { n: 17, week: 3, weekTheme: "Live in Command", focus: "Take the Seat", focusDesc: "Make the calls only you can make.", audioTitle: "Day 17: Lead From the Command Seat", audioDuration: "2:35", audioUrl: "/audio/day-17.m4a", reflection: "What decision have I been avoiding that only I can make?", action: "Make one leadership decision today, from clarity.", actionPrinciple: "Your business rises to the leadership you give it.", morningIntention: "I take the command seat. I lead with clarity and courage.", textNudge: "Indecision is more exhausting than a clear decision.", eveningReflection: "What did I decide as the leader today?", commandMove: "Make one leadership decision you've delayed." },
  { n: 18, week: 3, weekTheme: "Live in Command", focus: "Set the Tone", focusDesc: "Direct your business with intention.", audioTitle: "Day 18: The Power of Intention", audioDuration: "2:29", audioUrl: "/audio/day-18.m4a", reflection: "What intention do I want to lead from this season?", action: "Set one operating intention and keep it visible.", actionPrinciple: "Intention is the bridge between desire and creation.", morningIntention: "I move through my business with intention, aligned with my purpose.", textNudge: "Set the tone first; the day organizes around it.", eveningReflection: "Did my intention shape how I showed up?", commandMove: "Set and post one operating intention." },
  { n: 19, week: 3, weekTheme: "Live in Command", focus: "Make It Permanent", focusDesc: "Keep the vital few practices.", audioTitle: "Day 19: Integrate the System", audioDuration: "2:34", audioUrl: "/audio/day-19.m4a", reflection: "Which practices do I most want to make permanent?", action: "Choose 1–3 practices to keep and schedule them today.", actionPrinciple: "Transformation is a journey, not a destination.", morningIntention: "Command is simply how I run my business now.", textNudge: "Keep the vital few, kept consistently.", eveningReflection: "What will I carry past Day 21?", commandMove: "Schedule the 1–3 practices you'll keep." },
  { n: 20, week: 3, weekTheme: "Live in Command", focus: "Honor the Distance", focusDesc: "See how far you've come.", audioTitle: "Day 20: Reflect and Prepare for What's Next", audioDuration: "2:45", audioUrl: "/audio/day-20.m4a", reflection: "What are three real shifts I've experienced?", action: "Name your next chapter: one goal + one way to keep leading from command.", actionPrinciple: "Your vision is a living thing — it grows as you do.", morningIntention: "I lead confidently into what's next.", textNudge: "This isn't an ending — it's a threshold.", eveningReflection: "What am I most proud of?", commandMove: "Name your next chapter in one line." },
  { n: 21, week: 3, weekTheme: "Live in Command", focus: "Stand in Command", focusDesc: "You've made the shift.", audioTitle: "Day 21: Step Into Command", audioDuration: "2:56", audioUrl: "/audio/day-21.m4a", reflection: "What have I learned about myself as a leader?", action: "Celebrate the shift, and name your next step.", actionPrinciple: "From white-knuckling the hustle to hard-won harmony.", morningIntention: "I lead from command. I'm building a legacy, on purpose.", textNudge: "You came in hustling. You're leaving in command.", eveningReflection: "How will I keep leading from command?", commandMove: "Celebrate — and choose your next step." },
];

export const getDay = (n: number): Day | undefined => DAYS.find((d) => d.n === n);

/**
 * Structured outputs captured on specific days. These save to cs_outputs and become
 * the seed for the Command Suite assessments (Soul/Brain, Offer, Revenue, Brand, Positioning…).
 */
export type DayOutput = { key: string; label: string; placeholder: string };
export const DAY_OUTPUT: Record<number, DayOutput> = {
  2: { key: "mission_line", label: "Your mission line", placeholder: "Why this business exists — one honest sentence…" },
  3: { key: "command_audit", label: "Your Command Audit — two lowest areas", placeholder: "The two areas you circled, and a note on each…" },
  5: { key: "true_north", label: "Your True North (this season)", placeholder: "One clear destination for the next 90 days…" },
  8: { key: "offer", label: "Your core offer", placeholder: "Who it's for · the transformation · why it's worth it…" },
  9: { key: "revenue_friction", label: "Your #1 revenue friction", placeholder: "The one point in your buying path costing you the most…" },
  10: { key: "first_system", label: "The system you built", placeholder: "The repeatable checklist, template, or rule…" },
  11: { key: "brand_voice", label: "Your brand voice", placeholder: "Three words + a line in your true voice…" },
  12: { key: "positioning", label: "Your positioning line", placeholder: "I'm the ___ for ___ who want ___…" },
  18: { key: "operating_intention", label: "Your operating intention", placeholder: "How you choose to lead this season…" },
};
export const getDayOutput = (n: number): DayOutput | undefined => DAY_OUTPUT[n];
